DROP POLICY IF EXISTS "apks delete" ON storage.objects;
DROP POLICY IF EXISTS "apks update" ON storage.objects;
DROP POLICY IF EXISTS "apks upload" ON storage.objects;
DROP POLICY IF EXISTS "apks read via signed url" ON storage.objects;
DROP POLICY IF EXISTS "apks_delete_all" ON storage.objects;
DROP POLICY IF EXISTS "apks_update_all" ON storage.objects;
DROP POLICY IF EXISTS "apks_insert_all" ON storage.objects;
DROP POLICY IF EXISTS "apks_read_all" ON storage.objects;
DROP POLICY IF EXISTS "update counters" ON public.counters;
DROP POLICY IF EXISTS "read counters" ON public.counters;
DROP POLICY IF EXISTS "insert access_logs" ON public.access_logs;
DROP POLICY IF EXISTS "read access_logs" ON public.access_logs;
DROP POLICY IF EXISTS "insert download_logs" ON public.download_logs;
DROP POLICY IF EXISTS "read download_logs" ON public.download_logs;
DROP POLICY IF EXISTS "anyone upserts meta" ON public.apk_meta;
REVOKE EXECUTE ON FUNCTION public.increment_counter(text) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.reset_counter(text) FROM anon, authenticated, public;
GRANT EXECUTE ON FUNCTION public.increment_counter(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.reset_counter(text) TO service_role;
GRANT ALL ON public.counters, public.access_logs, public.download_logs, public.apk_meta TO service_role;